version: '0.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./CryptoGramBot/CryptoGramBot.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish --configuration release ./CryptoGramBot/CryptoGramBot.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\CryptoGramBot\bin\Release\netcoreapp2.0\publish'
   name: CryptoGramBot
   type: FolderProfile
clone_depth: 1
on_finish :
  # any cleanup in here
deploy:
  release: CryptoGramBot-v$(appveyor_build_version)
  description: 'Improve profit calcs (might not be fixed yet. Let me know), Poloniex balances, buy sell notifications, formatted dates, rounding.'
  provider: GitHub
  auth_token:
    secure: esN+SKR3Mla7CRA3bD9NBK1WFuuMc7W0/MyIX8kUC9q8BXELNvSZaBQcEt7S7oTj # your encrypted token from GitHub
  artifact: /.*\.zip/            # upload all zip packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false
